[package]
name = "iced-alegria"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
iced = { version = "0.13.1", default-features = false, features = [
    "tokio",
    "wgpu",
    "tiny-skia",
    "advanced",
    "image",
    "debug",     # TODO: Remove this on release
] }
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "postgres",
    "chrono",
    "uuid",
] }
dirs = "6.0.0" # TODO: I'm not using this since I'm not using Sqlite anymore, I'll keep it to create the config file in the correct path later (for now)
chrono = { version = "0.4.40", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
i18n-embed-fl = "0.9.3" # needed for fl support
rust-embed = "8.6.0" # needed for fl support
sweeten = { git = "https://github.com/airstrike/sweeten" } # needed for on_focus text input
iced_aw = { version = "0.12.2", default-features = false, features = [
    "date_picker",
] }
dotenvy = "0.15.7" # .env support
printers = "2.1.2" # getting printers, sending docs to print...
tokio = "1.44.2"
printpdf = "0.8.2" # pdf generation
fontdue = "0.9.3" # needed to measure the text width in order to print

[dependencies.i18n-embed]
version = "0.15.3"
features = ["fluent-system", "desktop-requester"]
