[package]
name = "iced-alegria"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", default-features = false, features = [
    "tokio",
    "wgpu",
    "tiny-skia",
    "advanced",
    "image",
    "debug",     # TODO: Remove this on release
] }
sqlx = { version = "0.8.3", features = [
    "runtime-tokio",
    "sqlite",
    "chrono",
    "uuid",
] }
futures = "0.3.31"
dirs = "6.0.0"
chrono = { version = "0.4.40", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
i18n-embed-fl = "0.9.3"
rust-embed = "8.6.0"
sweeten = { git = "https://github.com/airstrike/sweeten" } # needed for on_focus text input
iced_aw = { version = "0.12.2", default-features = false, features = [
    "date_picker",
] }

[dependencies.i18n-embed]
version = "0.15.3"
features = ["fluent-system", "desktop-requester"]
