# Allows crates to share monomorphized generic code instead of duplicating it.
# In some cases this allows us to "precompile" generic code so it doesn't affect iterative compiles.
# This is currently only available on nightly Rust
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    # Use lld linker on Linux
    # The Rust compiler spends a lot of time in the final "link" step, especially with a massive library like Bevy.
    # lld is much faster at linking than the default Rust linker.
    "-C",
    "link-arg=-fuse-ld=lld",
]

[alias]
lint = "clippy --workspace --benches --all-features --no-deps -- -D warnings"
lint-fix = "clippy --fix --allow-dirty --workspace --benches --all-features --no-deps -- -D warnings"
